steps:
  # 安裝依賴
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # 執行測試
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

# 指定這是一個自動觸發的構建
trigger:
  branch:
    - 'main'  # 或者是您用於開發的分支名稱，例如 'develop'

# 設置構建超時時間，例如 "1200s"，這是可選的，默認是 10 分鐘
timeout: '1200s'

# 這裡可以指定構建完成後的其他操作，例如通知，這是可選的
artifacts:
  objects:
    location: 'gs://your-bucket-name/artifacts/'
    paths: ['test-results/**']
