steps:
  # 安裝依賴
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      npm install

  # 執行測試
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      npm test

# 設置構建超時時間，例如 "1200s"，這是可選的，默認是 10 分鐘
timeout: '1200s'

# 這裡可以指定構建完成後的其他操作，例如通知，這是可選的
artifacts:
  objects:
    location: 'gs://jordantest/artifacts/'
    paths: ['test-results/**']
